version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_JAVA_OPTS=-Xmx1g
      - JENKINS_UPDATE_CENTER=https://updates.jenkins.io/update-center.json
    command: ["java", "-jar", "/usr/share/jenkins/jenkins.war"]
    tty: true
    stdin_open: true

  jenkins-agent:
    image: jenkins/inbound-agent:latest
    privileged: true
    depends_on:
      - jenkins
    environment:
      - JENKINS_AGENT_NAME=python-agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=jenkins-agent-secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["jenkins-agent", "-url", "http://jenkins:8080", "jenkins-agent-secret", "python-agent"]

volumes:
  jenkins_home:
